version: '3'
services:
  your_service:
    image: react-lol
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
        path: "/home/ubuntu/logs/container.log"
